#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
  path: /accueil
  controller: App\Controller\EtudiantController::index

etudiantAjouter:
    path: /etudiant/ajouter
    controller: App\Controller\EtudiantController::ajouterEtudiant

etudiantLister:
    path: /etudiant/lister
    controller: App\Controller\EtudiantController::listerEtudiant
